apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: qa
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: ravi2krishna/login:qa
        ports: 80
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: qa
spec:
  type: NodePort
  selector:
    app: login
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008 


