apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm
  namespace: qa
  labels:
    app: ecomm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecomm
  template:
    metadata:
      labels:
        app: ecomm
    spec:
      containers:
      - name: ecomm
        image: ravi2krishna/ecomm
        ports: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ecomm-service
  namespace: qa
spec:
  type: NodePort
  selector:
    app: ecomm
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008 


